baseurl = "https://ex7763.github.io"
languageCode = "zh"
title = "Lithium Theme"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-108871616-1"
disqusShortname = "ex7763"
canonifyurls = true

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

